<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ipkg</string>
	</array>
	<key>name</key>
	<string>Idris Ipkg</string>
	<key>patterns</key>
	<array>
        <dict>
			<key>match</key>
			<string>\b(brief|version|readme|license|author|maintainer|homepage|sourceloc|bugtracker)\b</string>
			<key>name</key>
			<string>constant.language.ipkg</string>
		</dict>
        <dict>
			<key>match</key>
			<string>\b(package|opts|modules|sourcedir|makefile|objs|executable|main|libs|pkgs)\b</string>
			<key>name</key>
			<string>keyword.control.ipkg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ipkg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ipkg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ipkg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ipkg</string>
	<key>uuid</key>
	<string>8957eeb1-b492-4497-85b8-b86e511e87eb</string>
</dict>
</plist>
